name = "stm32f0x0_hal"
description = "Drivers and HAL for stm32f0x0 mcu family"
version = "0.1.0"

authors = [" "]
licenses = "GPL-3.0-or-later AND BSD-3-Clause"
tags = ["embedded", "stm32f0", "nostd", "drivers"]
website = ""

[[depends-on]]
cortex_m = "~0.5"
hal = "~0.3"
usb_embedded = "*"
gnat_arm_elf = ">=12"

[[pins]]
usb_embedded = { path = "./usb_embedded/"}
[build-switches]
"*".style_checks = "No"


[configuration.variables]
Use_Startup = {type = "Boolean", default = true}

[configuration.values]
atomic.backend = "armv6m"
cortex_m.core = "m0"
